version: "3.8"

services:
  web:
    build:
      context: .
    image: web
    command: ./start
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/core/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    container_name: web
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - .env
    container_name: db

volumes:
  db_volume:
  static_volume:
  media_volume:
